---
title: "Performing Two-Sample Mean Comparison Using HMC"
# author: "Tianyu Zhang"
output: 
  html_document:
    theme: readable  # or try flatly, cerulean, journal, etc.
    css: |
      .container {
        max-width: 1200px;
        width: 95%;
      }
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 4
)

```

## Introduction

This tutorial demonstrates how to use the `HMC` package to perform high-dimensional mean comparison using data-driven projection and cross-fitting.

```{r}
rm(list = ls())
library(data.table)
library(HMC)
set.seed(123)
# Load data
output_dir <- "/Users/tianyuzhang/Documents/HMC/tutorial/"
residual_subset <- readRDS(paste0(output_dir, "/data/tiny_cleary_for_HMC.rds"))
clustering <- readRDS(paste0(output_dir, "/data/gene_clustering_for_HMC.rds"))

# Subset to control and treatment groups, then remove guide labels
control <- residual_subset[Guides_collapsed_by_gene == "non-targeting",
                           !"Guides_collapsed_by_gene"]
perturbed <- residual_subset[Guides_collapsed_by_gene == "STAT1",
                             !"Guides_collapsed_by_gene"]
```
Check the loaded data
```{r}
control[1:3, 1:5]
perturbed[1:3, 1:5]
```

Now apply the test:

```{r, message=FALSE, warning=FALSE, results='hide'}
gene_to_keep <- which(clustering$cluster_index == 31)
control_subset <- control[, ..gene_to_keep]
perturbed_subset <- perturbed[, ..gene_to_keep]
set.seed(1)
test_result <- mean_comparison_anchor(
              control = control_subset,
              treatment = perturbed_subset,
              pca_method = "sparse_pca",
              classifier_method = "lasso", 
              lambda_type = 'lambda.min',
              n_folds = 5,
              verbose = FALSE)
```

The p-value of the test is available, and we can list the features---genes in this case---that are used to distinguish the two groups.

I made some changes

```{r}
test_result$p_value
collect_active_features_proj(test_result)
```
